### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by g00s3mag1k** [g00s3mag1k/Horiseon-marketing-repo#1]
# User Story

AS a marketing agency
I WANT a codebase that follows accessibility standards
SO THAT our own site is optimized for search engines

## Acceptance Criteria

GIVEN a webpage meets accessibility standards
WHEN I view the source code
THEN I find semantic HTML elements
WHEN I view the heading attributes
THEN they fall in sequential order
WHEN I view the title element
THEN I find a concise, descriptive title
WHEN I view the icon and image elements
THEN I find accessible alt attributes

**Comment by Madanaa** [comment]
Hello!! @g00s3mag1k Can i do this?

**Comment by g00s3mag1k** [comment]
Hello! It's actually my class work so I have to do it but I appreciate the help! Honestly, best regards.
